// storybook/mock.ts
// Dados e objetos mock pro preview: plugin fake, app fake, conversas e
// mensagens de exemplo. Nada disso entra no bundle real.

import type { ChatSummary } from "../src/components/_shared/chatPersistence";
import type { ChatMessage } from "../src/store/chat";

// ── App fake (só o que os componentes tocam em render) ─────
export const mockApp: any = {
  vault: {
    getFiles: () => [],
    getAllLoadedFiles: () => [],
    getMarkdownFiles: () => [],
    adapter: { exists: async () => false },
    getAbstractFileByPath: () => null,
    getRoot: () => ({ path: "", children: [] }),
  },
  metadataCache: { getFileCache: () => null },
  workspace: { trigger: () => {}, openLinkText: () => {} },
};

// ── Plugin fake ────────────────────────────────────────────
const now = Date.now();
const daysAgo = (n: number) => new Date(now - n * 864e5).toISOString();

export const mockChats: ChatSummary[] = [
  {
    id: "c1",
    title: "Plano de conteúdo para o Q3",
    date: daysAgo(0),
    mode: "chat",
    provider: "openai",
    model: "gpt-5",
    effort: "med",
    tokensIn: 5230,
    tokensOut: 1810,
    messageCount: 14,
    filePath: "axxa-ai/chats/chat/c1.md",
  },
  {
    id: "c2",
    title: "Resumo das notas de reunião",
    date: daysAgo(1),
    mode: "vault-qa",
    provider: "openai",
    model: "gpt-4o",
    effort: "low",
    tokensIn: 12400,
    tokensOut: 940,
    messageCount: 6,
    filePath: "axxa-ai/chats/vault-qa/c2.md",
  },
  {
    id: "c3",
    title: "Refatorar estrutura do vault",
    date: daysAgo(2),
    mode: "agent",
    provider: "anthropic",
    model: "claude-sonnet-4-6",
    effort: "high",
    tokensIn: 30200,
    tokensOut: 8120,
    messageCount: 22,
    filePath: "axxa-ai/chats/agent/c3.md",
  },
  {
    id: "c4",
    title: "Ideias de nomes pro produto",
    date: daysAgo(4),
    mode: "chat",
    provider: "anthropic",
    model: "claude-haiku-4-5-20251001",
    effort: "low",
    tokensIn: 2100,
    tokensOut: 3400,
    messageCount: 9,
    filePath: "axxa-ai/chats/chat/c4.md",
  },
  {
    id: "c5",
    title: "Estudo: RAG local vs embeddings remotos",
    date: daysAgo(7),
    mode: "vault-qa",
    provider: "openai",
    model: "gpt-5",
    effort: "high",
    tokensIn: 44100,
    tokensOut: 12800,
    messageCount: 31,
    filePath: "axxa-ai/chats/vault-qa/c5.md",
  },
  {
    id: "c6",
    title: "Checklist de lançamento",
    date: daysAgo(12),
    mode: "chat",
    provider: "openai",
    model: "gpt-4o-mini",
    effort: "med",
    tokensIn: 900,
    tokensOut: 1500,
    messageCount: 5,
    filePath: "axxa-ai/chats/chat/c6.md",
  },
];

export const mockPlugin: any = {
  settings: {
    openaiApiKey: "sk-mock",
    anthropicApiKey: "sk-ant-mock",
    geminiApiKey: "",
    openrouterApiKey: "",
    nimApiKey: "",
    ollamaEndpoint: "",
    defaultProvider: "openai",
    defaultModel: "gpt-5",
    activeModels: {
      openai: ["gpt-4o", "gpt-4o-mini", "o3", "gpt-5"],
      anthropic: ["claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"],
      gemini: [],
      openrouter: [],
      nim: [],
      ollama: [],
    },
    favoriteModels: ["openai::gpt-5", "anthropic::claude-sonnet-4-6"],
    roleModels: {},
    modelProvider: {},
    discoveredEmbeddings: {},
    defaultMode: "chat",
    defaultEffort: "med",
    chatsPath: "axxa-ai/chats",
    skillsPath: "axxa-ai/skills",
    language: "en-us",
    background: "none",
    density: "normal",
    motion: "wave",
    reduceMotion: false,
    reducedMotionMobile: false,
    recordingsPath: "axxa-ai/recordings",
    notesPath: "axxa-ai/notes",
    responseStyle: "normal",
    projects: [],
    voiceURI: "",
    voiceRate: 1,
    voiceIntroDone: false,
    generationPath: "axxa-ai/generation",
    ragIndexPath: "axxa-ai/index",
    ragEmbeddingProvider: "openai",
    ragEmbeddingModel: "text-embedding-3-small",
    ragQuantProfile: "balanced",
    ragStreamShards: false,
    ragAutoReindex: false,
    codeWrap: false,
    agentPermissionLevel: "ask",
    agentDiffApproval: true,
    composerChips: ["model", "effort", "speed", "in", "out"],
    listChips: ["mode", "model", "date"],
    effortConfigs: {},
    mobileFullscreen: false,
    openaiDataSharing: false,
    openaiUsageTier: 1,
    openaiAdminKey: "",
    anthropicAdminKey: "",
    openaiProjectId: "",
    anthropicWorkspaceId: "",
    balanceAnchors: {},
    balanceCredits: {},
    accountTier: "pro",
    devTierOverride: "auto",
    founder: true,
    onboardingDone: true,
    licenseKey: "",
  },
  manifest: { version: "0.1.236" },
  vectorIndex: { size: 1284, model: "text-embedding-3-small" },
  chatSummaries: mockChats,
  fetchModelInfo: async () => null,
  saveSettings: async () => {},
  onSettingsChange: () => () => {},
  roleModel: () => null,
  loadChatSummaries: async () => mockChats,
  refreshDiscoveredEmbeddings: async () => {},
  reloadSkills: async () => {},
  seedExampleSkills: async () => {},
  skills: [],
  app: mockApp,
};

// ── Conversa de exemplo (Messages/ChatArea) ────────────────
export const mockMessages: ChatMessage[] = [
  {
    id: "m1",
    type: "user",
    timestamp: now - 6 * 60_000,
    content: "Me ajuda a organizar as notas da pesquisa de usuários? Quero um resumo dos temas que mais apareceram.",
  } as ChatMessage,
  {
    id: "m2",
    type: "ai-response",
    timestamp: now - 5 * 60_000,
    content: [
      "Claro! Analisando suas notas, os **três temas mais recorrentes** foram:",
      "",
      "1. **Onboarding confuso** — 8 menções, principalmente sobre a configuração inicial de API keys",
      "2. **Falta de feedback visual** — 5 menções durante operações longas (indexação, streaming)",
      "3. **Descoberta de recursos** — 4 menções; usuários não sabiam que o modo *Vault Q&A* existia",
      "",
      "Sugestão de próximo passo:",
      "",
      "```md",
      "- [ ] Criar um onboarding guiado de 3 passos",
      "- [ ] Adicionar progresso visível na indexação RAG",
      "- [ ] Destacar os modos na tela inicial",
      "```",
      "",
      "Quer que eu crie uma nota consolidada com isso em [[Pesquisa/Resumo-Temas]]?",
    ].join("\n"),
    reasoning: "O usuário quer um resumo temático. Vou agrupar as menções por frequência e propor ações concretas, mantendo formato escaneável com lista numerada.",
    model: "gpt-5",
    provider: "openai",
  } as unknown as ChatMessage,
  {
    id: "m3",
    type: "user",
    timestamp: now - 3 * 60_000,
    content: "Cria sim, e adiciona uma seção com citações diretas dos usuários.",
  } as ChatMessage,
  {
    id: "m4",
    type: "ai-comment",
    timestamp: now - 2 * 60_000,
    content: "",
    activity: {
      phase: "done",
      iconPending: "file-plus",
      iconDone: "check",
      pendingText: "Criando nota…",
      doneText: "Nota criada: Pesquisa/Resumo-Temas.md",
    },
  } as unknown as ChatMessage,
  {
    id: "m5",
    type: "ai-response",
    timestamp: now - 60_000,
    content: "Pronto! Criei a nota **Resumo-Temas** com os três temas, as ações sugeridas e uma seção *Citações* com as 6 falas mais representativas. Quer que eu vincule ela ao seu MOC de pesquisa?",
    model: "gpt-5",
    provider: "openai",
  } as unknown as ChatMessage,
];

export const mockErrorMessage: ChatMessage = {
  id: "e1",
  type: "ai-response",
  timestamp: now,
  content: "",
  isError: true,
  errorCode: "invalid-key",
} as unknown as ChatMessage;
